// layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { EnvProvider } from "@/env/provider";
import { EnvConfig } from "@/env/env";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    env?: EnvConfig;
  };
}

const RootLayout: React.FC<RootLayoutProps> = ({ children, params }) => {
  console.log("RootLayout params:", params);
  if(params.env) {
    return (
      <div>
        <EnvProvider env={params.env}>{children}</EnvProvider>
      </div>
    );
  } else {
    return (
      <html lang="en">
        <body>
          <EnvProvider>{children}</EnvProvider>
        </body>
      </html>
    );
  }
};

export default RootLayout;
